In [82]:
import sys
sys.path.append("..")

from extract.api import (
    autenticacao_url,
    buscar_voos_brasil,
    buscar_chegadas_voos,
    buscar_partidas_voos,
    intervalo_de_tempos_voos,
    TOKEN_URL,
    LOCALIZACAO_URL,
    CHEGADAS_URL,
    PARTIDAS_URL,
    INTERVALO_URL
)

token     = autenticacao_url(TOKEN_URL)
local     = buscar_voos_brasil(token, LOCALIZACAO_URL)
chegadas = buscar_chegadas_voos(token, 1753484400, 1753570800)
partidas  = buscar_partidas_voos(token, PARTIDAS_URL)
intervalo = intervalo_de_tempos_voos(token, INTERVALO_URL)

print(local["states"])
print(chegadas)
print(partidas)
print(intervalo)

TypeError: buscar_chegadas_voos() takes 2 positional arguments but 3 were given

In [ ]:
import pandas as pd

COLUNAS_VOOS = [
    "icao24",
    "callsign",
    "origin_country",
    "time_position",
    "last_contact",
    "longitude",
    "latitude",
    "baro_altitude",
    "on_ground",
    "velocity",
    "true_track",
    "vertical_rate",
    "sensors",
    "geo_altitude",
    "squawk",
    "spi",
    "position_source"
]

df_voos = pd.DataFrame(local["states"], columns=COLUNAS_VOOS)
print(df_voos.shape)
df_voos.head(200)

(156, 17)

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,e80268,ARE4907,Chile,1785365968,1785365968,-47.4750,-23.0493,5791.20,False,166.43,108.94,0.00,None,6118.86,None,False,0
1,e80278,LPE2425,Chile,1785365967,1785365967,-49.3230,-22.3774,10645.14,False,191.58,286.54,4.88,None,11163.30,None,False,0
2,e80210,LPE2935,Chile,1785365967,1785365967,-47.0705,-23.0638,5783.58,False,187.18,42.33,-1.95,None,6088.38,None,False,0
3,e48be3,TAM3818,Brazil,1785365968,1785365968,-48.6420,-27.6168,548.64,False,78.09,121.81,-4.23,None,594.36,7136,True,0
4,e49ec9,AZU4787,Brazil,1785365963,1785365967,-44.8874,-16.2586,11582.40,False,236.57,166.42,0.00,None,12275.82,None,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,0c2195,DAE925,Panama,1785365967,1785365967,-54.6293,-12.7823,10675.62,False,245.94,150.97,-0.33,None,11323.32,None,False,0
152,39d2b5,AFR459,France,1785365967,1785365968,-46.2030,-23.3880,4693.92,False,190.64,45.87,8.45,None,4937.76,None,False,0
153,0c2167,CMP800,Panama,1785365956,1785365956,-70.4473,-2.1145,9448.80,False,240.91,159.63,0.00,None,10096.50,None,False,0
154,4b18e4,SWW1C,Switzerland,1785365966,1785365966,-71.8211,-7.0131,12496.80,False,235.39,45.97,0.00,None,13281.66,None,False,0
155,e94c88,BOV777,Bolivia,1785365967,1785365967,-55.5363,-11.3279,12192.00,False,226.49,229.14,0.00,None,12938.76,None,False,0

In [ ]:
# chegadas
df_chegadas = pd.DataFrame(chegada)
print("=== CHEGADAS ===")
print(df_chegadas.shape)
df_chegadas.head(200)

=== CHEGADAS ===
(5, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e48014,1517226160,SBPA,1517230454,SBGR,TAM3297,14816.0,1253.0,1881,27,0,2
1,e48c05,1517227012,None,1517229023,SBGR,GLO1119,NaN,NaN,2047,35,0,2
2,a1f90e,1517195991,KEWR,1517228811,SBGR,UAL149,1189.0,81.0,3296,111,1,2
3,e491b0,1517203852,SBBE,1517228288,SBGR,TAM3325,916.0,120.0,2067,27,1,2
4,e491a2,1517226455,SBKP,1517227486,SBGR,TAM3212,1644.0,131.0,2188,27,0,2

In [ ]:
# intervalo
df_intervalo = pd.DataFrame(intervalo)
print("=== INTERVALO ===")
print(df_intervalo.shape)
df_intervalo.head(200)

=== INTERVALO ===
(472, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,84630c,1517229441,None,1517230681,None,JJP120,NaN,NaN,NaN,NaN,0,0
1,800547,1517227477,VGTJ,1517228618,None,JAI273,6958.0,655.0,NaN,NaN,1,0
2,a403ca,1517228212,None,1517229651,None,None,NaN,NaN,NaN,NaN,0,0
3,0c6018,1517227972,KJFK,1517229448,None,None,7899.0,1161.0,NaN,NaN,0,0
4,abc2e5,1517228209,KEWR,1517229988,None,RPA3598,2093.0,89.0,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,c078fd,1517227317,CYYZ,1517230676,CYUL,SWG9426,525.0,104.0,3244.0,81.0,1,1
196,8686b2,1517229296,None,1517230536,RJTK,JAL920,NaN,NaN,15167.0,1421.0,0,1
197,e491f0,1517229076,None,1517230486,SBMT,ONE6105,NaN,NaN,6467.0,566.0,0,2
198,3e3a2c,1517227395,EDFZ,1517228367,EDRI,DINFO,2059.0,175.0,12600.0,1638.0,0,2
199,4ca88c,1517227634,None,1517230768,None,RYR55HX,NaN,NaN,NaN,NaN,0,0

In [ ]:
df_partidas = pd.DataFrame(partidas)
print("===PARTIDAS===")
print(df_partidas.shape)
df_partidas.head()

===PARTIDAS===
(29, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e48b65,1517230782,SBGR,1517234419,SBVT,TAM3362,6200,355,340.0,11.0,0,0
1,e48f6a,1517230697,SBGR,1517241394,SBBE,TAM3554,6196,363,2019.0,67.0,0,1
2,e48dc1,1517230612,SBGR,1517234572,None,TAM9006,5788,393,NaN,NaN,0,0
3,0d09ec,1517230461,SBGR,1517248678,None,AMX015,6071,500,NaN,NaN,0,0
4,e48618,1517230344,SBGR,1517238618,SUMU,GLO7630,8080,644,4792.0,135.0,0,1