In [ ]:
import sys
sys.path.append("..")

from extract.api import (
    autenticacao_url,
    buscar_voos_brasil,
    buscar_chegadas_voos,
    buscar_partidas_voos,
    intervalo_de_tempos_voos,
    TOKEN_URL,
    LOCALIZACAO_URL,
    INTERVALO_URL
)

token     = autenticacao_url(TOKEN_URL)
local     = buscar_voos_brasil(token, LOCALIZACAO_URL)
chegadas = buscar_chegadas_voos(token, 1753484400, 1753570800)
partidas  = buscar_partidas_voos(token, 1753484400, 1753570800)
intervalo = intervalo_de_tempos_voos(token, 1753484400, 1753570800)

# print(local["states"])
print(chegadas)
print(partidas)
# print(intervalo)

SBGR: chegadas:378 voos
SBGL: chegadas:218 voos
SBBR: chegadas:135 voos
SBGR: saidas:272 voos
SBGL: saidas:166 voos
SBBR: saidas:117 voos

In [6]:
import pandas as pd

COLUNAS_VOOS = [
    "icao24",
    "callsign",
    "origin_country",
    "time_position",
    "last_contact",
    "longitude",
    "latitude",
    "baro_altitude",
    "on_ground",
    "velocity",
    "true_track",
    "vertical_rate",
    "sensors",
    "geo_altitude",
    "squawk",
    "spi",
    "position_source"
]

df_voos = pd.DataFrame(local["states"], columns=COLUNAS_VOOS)
print(df_voos.shape)
df_voos.head(200)

(157, 17)

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,e80251,LPE2453,Chile,1785368651,1785368651,-73.2855,5.0180,10988.04,False,228.75,199.17,0.00,None,11750.04,None,False,0
1,e80278,LPE2425,Chile,1785368651,1785368651,-54.1213,-20.9689,10972.80,False,196.36,288.48,0.33,None,11544.30,None,False,0
2,e80273,LPE2368,Chile,1785368651,1785368651,-59.8364,-32.6741,9753.60,False,219.03,326.98,0.00,None,10073.64,0513,False,0
3,e49ed4,TAM3012,Brazil,1785368652,1785368652,-47.0949,-23.5301,5867.40,False,166.34,333.75,13.33,None,6179.82,None,False,0
4,e49f45,AZU2921,Brazil,1785368652,1785368652,-46.3162,-21.4764,8839.20,False,207.92,197.72,0.00,None,9326.88,None,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,0c2083,CMP207,Panama,1785368651,1785368651,-71.1800,-5.5023,10668.00,False,238.32,144.05,0.00,None,11399.52,None,False,0
153,0c205b,CMP745,Panama,1785368650,1785368650,-72.6780,-2.6987,10668.00,False,242.17,156.59,0.00,None,11407.14,None,False,0
154,0c208e,CMP205,Panama,1785368597,1785368597,-71.0828,-1.0024,10668.00,False,235.15,145.79,0.00,None,11391.90,None,False,0
155,e94c86,BOV735,Bolivia,1785368651,1785368651,-47.0134,-23.6809,6256.02,False,200.90,272.94,10.08,None,6568.44,None,False,0
156,e94c88,BOV777,Bolivia,1785368567,1785368567,-59.6329,-14.7904,12192.00,False,224.09,229.66,0.00,None,12946.38,None,False,0

In [9]:
# chegadas
df_chegadas = pd.DataFrame(chegadas)
print("=== CHEGADAS ===")
print(df_chegadas.shape)
df_chegadas.head(200)

# Todos aeroportos foram contabilizados
# df_chegadas["estArrivalAirport"].unique()

=== CHEGADAS ===
(731, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e80478,1753550901,SKBO,1753570215,SBGR,ARE4907,830.0,49.0,8211,286,1,2
1,e8043c,1753545991,SAEZ,1753569951,SBGR,LAN742,853.0,12.0,8709,317,2,2
2,e4925f,1753565241,SBBR,1753569773,SBGR,TAM3256,2337.0,176.0,9102,324,1,2
3,e486c2,1753550980,SBFZ,1753569658,SBGR,TAM3491,492.0,35.0,8761,317,1,2
4,e49914,1753566119,None,1753569517,SBGR,PSASF,NaN,NaN,8288,309,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
195,e49aaa,1753525062,None,1753526788,SBGR,TAM3283,NaN,NaN,8028,279,0,2
196,e48986,1753524412,None,1753526609,SBGR,GLO1241,NaN,NaN,8015,279,0,2
197,e48e09,1753521660,SBBR,1753526458,SBGR,GLO1409,2677.0,0.0,7907,271,1,2
198,e8046f,1753497296,KMCO,1753525996,SBGR,TAM8127,2851.0,100.0,9201,340,0,2
199,e48e92,1753523762,None,1753525856,SBGR,GLO1101,NaN,NaN,8403,294,0,2

In [10]:
# intervalo
df_intervalo = pd.DataFrame(intervalo)
print("=== INTERVALO ===")
print(df_intervalo.shape)
df_intervalo.head(200)

=== INTERVALO ===
(472, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e48bb0,1517227957,SBSP,1517229087,None,ONE6004,5036.0,493.0,NaN,NaN,1,0
1,05a02e,1517227761,VRMM,1517228622,None,8QMBD,1604.0,74.0,NaN,NaN,0,0
2,491146,1517229250,LPPT,1517229984,None,TAP1102,4966.0,716.0,NaN,NaN,2,0
3,49d3f9,1517228777,LKPR,1517229614,LKHV,OKHHH,1148.0,113.0,5730.0,186.0,0,2
4,a31e36,1517228758,KHPN,1517230090,KOQU,N30NS,519.0,11.0,24871.0,1076.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
195,c078fd,1517227317,CYYZ,1517230676,CYUL,SWG9426,525.0,104.0,3244.0,81.0,1,1
196,8686b2,1517229296,None,1517230536,RJTK,JAL920,NaN,NaN,15167.0,1421.0,0,1
197,e491f0,1517229076,None,1517230486,SBMT,ONE6105,NaN,NaN,6467.0,566.0,0,2
198,3e3a2c,1517227395,EDFZ,1517228367,EDRI,DINFO,2059.0,175.0,12600.0,1638.0,0,2
199,4ca88c,1517227634,None,1517230768,None,RYR55HX,NaN,NaN,NaN,NaN,0,0

In [14]:
df_partidas = pd.DataFrame(partidas)
print("===PARTIDAS===")
print(df_partidas.shape)
df_partidas.head(100)

df_partidas["estDepartureAirport"].unique()

===PARTIDAS===
(555, 12)

array(['SBGR', 'SBGL', 'SBBR'], dtype=object)