In [9]:
import sys
sys.path.append("..")

from extract.api import (
    autenticacao_url,
    buscar_voos_brasil,
    buscar_chegadas_voos,
    buscar_partidas_voos,
    intervalo_de_tempos_voos,
    TOKEN_URL,
    LOCALIZACAO_URL,
    INTERVALO_URL
)

token     = autenticacao_url(TOKEN_URL)
local     = buscar_voos_brasil(token, LOCALIZACAO_URL)
chegadas = buscar_chegadas_voos(token, 1753484400, 1753570800)
partidas  = buscar_partidas_voos(token, 1753484400, 1753570800)
intervalo = intervalo_de_tempos_voos(token, INTERVALO_URL)

print(local["states"])
print(chegadas)
# print(partidas)
# print(intervalo)

bug aqui
SBGR: 378 voos
bug aqui
SBGL: 218 voos
bug aqui
SBBR: 135 voos

TypeError: buscar_partidas_voos() takes 2 positional arguments but 3 were given

In [ ]:
import pandas as pd

COLUNAS_VOOS = [
    "icao24",
    "callsign",
    "origin_country",
    "time_position",
    "last_contact",
    "longitude",
    "latitude",
    "baro_altitude",
    "on_ground",
    "velocity",
    "true_track",
    "vertical_rate",
    "sensors",
    "geo_altitude",
    "squawk",
    "spi",
    "position_source"
]

df_voos = pd.DataFrame(local["states"], columns=COLUNAS_VOOS)
print(df_voos.shape)
df_voos.head(200)

(152, 17)

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source
0,e80268,ARE4907,Chile,1785367445,1785367445,-46.1940,-23.3594,1485.90,False,68.69,253.47,-0.65,None,1592.58,None,False,0
1,e80210,LPE2935,Chile,1785367442,1785367444,-46.3703,-23.4073,1196.34,False,69.33,253.18,-2.93,None,1272.54,None,False,0
2,e07584,ARG1364,Argentina,1785367081,1785367311,-63.6396,-28.2739,11582.40,False,221.69,317.16,0.00,None,12031.98,1745,False,0
3,e49eef,GLO1350,Brazil,1785367445,1785367445,-45.6786,-23.4712,6446.52,False,207.63,61.59,10.73,None,6774.18,None,False,0
4,e49ef4,GLO2178,Brazil,1785367445,1785367445,-44.9652,-23.2716,9448.80,False,274.77,76.80,-0.33,None,9936.48,None,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,0c2167,CMP800,Panama,1785367409,1785367409,-68.6159,-4.6447,10668.00,False,245.99,136.53,0.00,None,11399.52,None,False,0
148,0c2166,CMP283,Panama,1785367446,1785367446,-72.2762,-4.1688,10668.00,False,239.41,159.89,0.00,None,11391.90,None,False,0
149,4b18e4,SWW1C,Switzerland,1785367445,1785367445,-69.5729,-4.8277,12496.80,False,230.28,45.63,0.00,None,13281.66,None,False,0
150,0c2083,CMP207,Panama,1785367445,1785367445,-72.4787,-3.2752,10668.00,False,243.01,154.68,0.00,None,11399.52,None,False,0
151,e94c88,BOV777,Bolivia,1785367445,1785367445,-57.8627,-13.3113,12192.00,False,226.16,229.24,0.00,None,12946.38,None,False,0

In [ ]:
# chegadas
df_chegadas = pd.DataFrame(chegadas)
print("=== CHEGADAS ===")
print(df_chegadas.shape)
df_chegadas.head(200)

df_chegadas["estArrivalAirport"].unique()

=== CHEGADAS ===
(731, 12)

array(['SBGR', 'SBGL', 'SBBR'], dtype=object)

In [ ]:
# intervalo
df_intervalo = pd.DataFrame(intervalo)
print("=== INTERVALO ===")
print(df_intervalo.shape)
df_intervalo.head(200)

=== INTERVALO ===
(472, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,84630c,1517229441,None,1517230681,None,JJP120,NaN,NaN,NaN,NaN,0,0
1,800547,1517227477,VGTJ,1517228618,None,JAI273,6958.0,655.0,NaN,NaN,1,0
2,a403ca,1517228212,None,1517229651,None,None,NaN,NaN,NaN,NaN,0,0
3,0c6018,1517227972,KJFK,1517229448,None,None,7899.0,1161.0,NaN,NaN,0,0
4,abc2e5,1517228209,KEWR,1517229988,None,RPA3598,2093.0,89.0,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,c078fd,1517227317,CYYZ,1517230676,CYUL,SWG9426,525.0,104.0,3244.0,81.0,1,1
196,8686b2,1517229296,None,1517230536,RJTK,JAL920,NaN,NaN,15167.0,1421.0,0,1
197,e491f0,1517229076,None,1517230486,SBMT,ONE6105,NaN,NaN,6467.0,566.0,0,2
198,3e3a2c,1517227395,EDFZ,1517228367,EDRI,DINFO,2059.0,175.0,12600.0,1638.0,0,2
199,4ca88c,1517227634,None,1517230768,None,RYR55HX,NaN,NaN,NaN,NaN,0,0

In [ ]:
df_partidas = pd.DataFrame(partidas)
print("===PARTIDAS===")
print(df_partidas.shape)
df_partidas.head()

===PARTIDAS===
(29, 12)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e48b65,1517230782,SBGR,1517234419,SBVT,TAM3362,6200,355,340.0,11.0,0,0
1,e48f6a,1517230697,SBGR,1517241394,SBBE,TAM3554,6196,363,2019.0,67.0,0,1
2,e48dc1,1517230612,SBGR,1517234572,None,TAM9006,5788,393,NaN,NaN,0,0
3,0d09ec,1517230461,SBGR,1517248678,None,AMX015,6071,500,NaN,NaN,0,0
4,e48618,1517230344,SBGR,1517238618,SUMU,GLO7630,8080,644,4792.0,135.0,0,1